# Generated by Django 2.2.15 on 2020-09-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='senti_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='senti_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
